package com.example.mysamsungapp.sdkhealthconnect

import androidx.health.connect.client.records.*

interface HealthConnectCallback {
    fun onAvailableHC(boolean: Boolean)
    fun onPermissionGranted(boolean: Boolean)
    fun onReceiveHRData(heartRateRecord: List<HeartRateRecord>)
    fun onReceiveCaloriesBurned(caloriesBurnedRecord: List<ActiveCaloriesBurnedRecord>)
    fun onReceivedBasalBodyTempt(basalBodyTempRecord: List<BasalBodyTemperatureRecord>)
    fun onReceivedBasalMetabolicrate(basalMetabolicRateRecord: List<BasalMetabolicRateRecord>)
    fun onReceiveBloodGlucose(bloodGlucoseRecord: List<BloodGlucoseRecord>)
    fun onReceiveBloodPressure(bloodPressureRecord: List<BloodPressureRecord>)
    fun onReceiveBodyFat(bodyFat: List<BodyFatRecord>)
    fun onReceivedBodyTemper(bodyTemperatureRecord: List<BodyTemperatureRecord>)
    fun onReceiveBoneMass(boneMassRecord: List<BoneMassRecord>)
    fun onReceiveCervicalMucus(cervicalMucusRecord: List<CervicalMucusRecord>)
    fun onReceiveCyclingPedalingCadence(cyclingPedalingCadenceRecord: List<CyclingPedalingCadenceRecord>)
    fun onReceiveDistance(distanceRecord: List<DistanceRecord>)
    fun onReceiveElevationGained(elevationGainedRecord: List<ElevationGainedRecord>)
    fun onReceiveExerciseSession(exerciseSessionRecord: List<ExerciseSessionRecord>)
    fun onReceiveFloorsClimbed(floorsClimbedRecord: List<FloorsClimbedRecord>)
    fun onReceiveHeight(heightRecord: List<HeightRecord>)
    fun onReceiveHydration(hydrationRecord: List<HydrationRecord>)
    fun onReceiveLeanBodyMass(leanBodyMassRecord: List<LeanBodyMassRecord>)
    fun onReceiveMenstruationFLow(menstruationFlowRecord: List<MenstruationFlowRecord>)
    fun onReceiveNutrition(nutritionRecord: List<NutritionRecord>)
    fun onReceiveOvulationTest(ovulationTestRecord: List<OvulationTestRecord>)
    fun onReceiveOxygenSaturation(oxygenSaturationRecord: List<OxygenSaturationRecord>)
    fun onReceivePower(powerRecord: List<PowerRecord>)
    fun onReceiveRespirationRate(respiratoryRateRecord: List<RespiratoryRateRecord>)
    fun onReceiveRestingHearRate(restingHeartRateRecord: List<RestingHeartRateRecord>)
    fun onReceiveSexualActivity(sexualActivityRecord: List<SexualActivityRecord>)
    fun onReceiveSleepSession(sleepSessionRecord: List<SleepSessionRecord>)
    fun onReceiveSleepStage(sleepStageRecord: List<SleepStageRecord>)
    fun onReceiveSpeed(speedRecord: List<SpeedRecord>)
    fun onReceiveStepsCadence(stepsCadenceRecord: List<StepsCadenceRecord>)
    fun onReceiveStep(stepsRecord: List<StepsRecord>)
    fun onReceiveTotalCaloriesBurned(totalCaloriesBurnedRecord: List<TotalCaloriesBurnedRecord>)
    fun onReceiveVo2Max(vo2MaxRecord: List<Vo2MaxRecord>)
    fun onReceiveWeight(weightRecord: List<WeightRecord>)
    fun onReceiveWheelChairPushes(wheelchairPushesRecord: List<WheelchairPushesRecord>)
}